spring:
  application:
    name:                       Hackathon

  datasource:
    driver-class-name:          com.mysql.jdbc.Driver
    url:                        jdbc:mysql://127.0.0.1:3306/db
    username:                   root
    password:                   root

  jpa:
    properties:
      hibernate:
        dialect:                org.hibernate.dialect.MySQLDialect
    show-sql:                   false

app:
  first-name: Antonel-Ernest
  last-name: Pazargic

